### ISSUE TITLE
one tap login with issues requires feature (auth_api_credentials_begin_sign_in, 7)

### ISSUE THREAD

**Issue by Yetland** [stevdza-san/OneTapCompose#1]
I am trying to use this lib to one tap login.
I got a problem
```
com.google.android.gms.internal.auth-api.zbaz could not execute call because it requires feature (auth_api_credentials_begin_sign_in, 7).
Google Account not Found.
```
I only change the web_client_id.
Can you help me to figure it out ?

**Comment by stevdza-san** [comment]
If you check this answer you'll see that you need to add your WEB Client ID and not ANDROID: https://stackoverflow.com/questions/74558656/missing-featurename-auth-api-credentials-begin-sign-in-version-7

Also try rebuilding the project/clearing the cache before retrying again.
Btw be sure to test it on a real device as well, because emulators are experiencing some issues with that API.

**Comment by Yetland** [comment]
> If you check this answer you'll see that you need to add your WEB Client ID and not ANDROID: https://stackoverflow.com/questions/74558656/missing-featurename-auth-api-credentials-begin-sign-in-version-7
> 
> Also try rebuilding the project/clearing the cache before retrying again. Btw be sure to test it on a real device as well, because emulators are experiencing some issues with that API.

after I change my web client id and my code with the answer, it works for me.
I am trying to change your lib to my applicationId and signing config to my own, it not works at all,  I get the same logs.

**Comment by stevdza-san** [comment]
What application id and signing config, I don't follow?

**Comment by Yetland** [comment]
https://stackoverflow.com/questions/74558656/missing-featurename-auth-api-credentials-begin-sign-in-version-7 
this answer helps me.
but I still can't  use your lib with the same error.

**Comment by stevdza-san** [comment]
Please try running your app on a real device, it should work.
Like I said, android emulators are having issues with Google accounts in a strange way.

**Comment by litov74** [comment]
@stevdza-san 
I checked google bug reports and everybody says that with every new versions percentage of getting this error is growing.
I tried at least all versions of play-services-auth and only one works with 2-4% of errors.

Just set the dependency version to 19.0.0 and it'll work)
