### ISSUE TITLE
tapping Sign In flashes the button but nothing else.

### ISSUE THREAD

**Issue by davehorner** [stevdza-san/OneTapCompose#10]
Just giving this a try.  Updated my clientId.  Built fine.
I do see that state.open() is getting called onClick.
Not sure what else to do.

**Comment by stevdza-san** [comment]
Check whether you've got the right package name and SHA-1 certificate fingerprint in your GCP project.

**Comment by davehorner** [comment]
Hmm. Yes I have verified and created another project to verify.

```
                launchActivityResult(
                    IntentSenderRequest.Builder(
                        result.pendingIntent.intentSender
                    ).build()
```
the above is being called, it flashes the screen and nothing more.  I do not see anything in logcat.  I will keep trying...

**Comment by davehorner** [comment]
Thank you for the note.  I was able to get it working and it was in fact a SHA1 issue.

I have the token and I'm now trying to figure out how to use it with the google calendar api.
I pass in the token from the onTokenIdReceived; I found the token to be the exact same as comes from GoogleSignIn.idToken
```
   fun calendar(tokenId: String) {
        viewModelScope.launch {
            val result = withContext(Dispatchers.IO) {
        val transport = GoogleNetHttpTransport.newTrustedTransport()
        val jsonFactory = GsonFactory.getDefaultInstance()

        // Get the GoogleSignInAccount from the GoogleSignInClient
        val account = GoogleSignIn.getLastSignedInAccount(context)

        if (account != null) {
            val scopes=account.grantedScopes
            // Use the GoogleSignInAccount's idToken as the credential
            val credential = if (tokenId.length > 0) tokenId else account.idToken

            Log.d("OAuthToken", credential ?: "Token is null")
                mCalendar = Calendar.Builder(
                    transport, jsonFactory, null
                )
                    .setApplicationName("GetEventCalendar")
                    .setHttpRequestInitializer { request ->
                        // Add the idToken as an Authorization header
                        request.headers.authorization = "Bearer $credential"
                    }
                    .build()

                try {
                    // the application exception 401 occurs here
                    val calendarList = mCalendar!!.calendarList().list().execute()

                } catch (e: Exception) {
                    e.printStackTrace()
                }
        } else {
            // Handle the case where there is no signed-in Google account
        }
        }
    }
```

I see request.headers.authorization = "Bearer $credential" being called and adding the oauth token.
"message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential"

Google Calendar API is enabled in the GCP project and I can read from the calendars in other apps using the same project.

I understand this is beyond the scope of the OneTapCompose; I figured I'd ask in case you can think of anything.
Nice work, it took me a bit to get the code to come down with build.gradle.kts

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        snapshotVersion?.let {
            println("https://androidx.dev/snapshots/builds/$it/artifacts/repository/") 
            maven { url = uri("https://androidx.dev/snapshots/builds/$it/artifacts/repository/") }
        }
        google()
        mavenCentral()
        maven { setUrl("https://jitpack.io") }
    }
}
```
its actually in settings.gradle.kts; maybe worth adding to the readme. idk, figured I'm mention the other thing.

**Comment by davehorner** [comment]
Ok, because I had so much trouble getting the OneTap sign in to work, I also implemented via GoogleSignIn.  
Took me like a week but I finally figured out how to get GoogleSignIn working with the google calendar.

In this case I'm using GoogleAccountCredential.usingOAuth2 .setSelectedAccount to pass in the account from GoogleSignIn.  You end up specing the calendar scope on the GoogleSignInOptions.Builder and then again using GoogleAccountCredential.usingOAuth2.  I'm unsure how to spec the scope when using OneTapSignInWithGoogle.
```
                val mCredential = GoogleAccountCredential.usingOAuth2(
                    context,
                    arrayListOf(CalendarScopes.CALENDAR)
                ).setSelectedAccount(account?.account)

                mCalendar = Calendar.Builder(
                    transport, jsonFactory,  null
                )
                    .setHttpRequestInitializer { request ->
                        request.headers.set("Authorization","Bearer ${mCredential.token}")
                    }
                    .build()
```
When I use the OneTapSignInWithGoogle onTokenIdReceived and get the tokenId; what's the best way to get the ultimate token that should be presented in Bearer? I have it working with GoogleSignIn, but I'd like it to work with your OneTapSignInWithGoogle.  thanks.

**Comment by tasvanth** [comment]
Create OneTapSignin and onetapsigninstate files locally and edit as required.

**Comment by stevdza-san** [comment]
@davehorner I'm glad you've figured it out eventually. But I don't think there's a way of specifying the "scope" with OneTap API. Correct me if I'm wrong?

**Comment by davehorner** [comment]
@tasvanth  I'm not sure I follow, there's no edits that I need to make in the code that I can see.

@stevdza-san I don't see a way...which makes me wonder how to use it with a scope.  I also don't know how to get the token.  Your code does work and the flow accepts and gets the access token but I don't know how to use it from there

I'm not really sure what is the point of one tap if you can't get a scope

**Comment by stevdza-san** [comment]
OneTap API is made for a fast authorization, to sign in with google and get the tokenId. You can then use that tokenId to extract the information from a user. You can't use "scopes" with this API as far as I know. You would have to use different API for that matter.

**Comment by davehorner** [comment]
https://stackoverflow.com/questions/73583035/obtaining-googlecredentials-from-one-tap-signin comes with an implementation https://github.com/Ellie-Coding/google-one-tap-drive is not compose example but it shows some integration.

He's creating the AccountManager Account directly from the id and packageName...not sure why the packageName is of importance to this.
```
           val oneTapCredential: SignInCredential =
                oneTapClient.getSignInCredentialFromIntent(data)
            Log.d(TAG, "Signed in as " + oneTapCredential.displayName)
            userViewModel.saveLoginSuccess(this, Account(oneTapCredential.id, packageName))
```

```
            GoogleAccountCredential.usingOAuth2(
                context, Collections.singleton(DriveScopes.DRIVE_APPDATA)
            ).setSelectedAccount(account)
```
It's been fun.  lol  I'm probably done for a while, maybe this info helps someone else.  have a great night.
