### ISSUE TITLE
OneTapCompose not Working on App Release

### ISSUE THREAD

**Issue by azickri** [stevdza-san/OneTapCompose#14]
When I tried OneTapCompose in debug mode it ran fine. But when I build with release it always goes to onDialogDismissed.

My Code 
```
...
            OneTapSignInWithGoogle(
                state = oneTapSignInGoogleState,
                clientId = LocalContext.current.getString(R.string.google_client_id),
                rememberAccount = false,
                onTokenIdReceived = { tokenId ->
                    authViewModel.setStateLogin("google")

                    val user: GoogleUser? = getUserFromTokenId(tokenId)
                    if (user != null) {
                        authViewModel.googleLogin(code = "android_google_code", email = user.email, name = user.fullName)
                    } else {
                        authViewModel.resetState()
                        showSnackbar(message = "Autentikasi Google Gagal. User Null", scope, snackbarHostState)
                    }
                },
                onDialogDismissed = {
                    authViewModel.resetState()
                    showSnackbar(message = "Autentikasi Google Dibatalkan", scope, snackbarHostState)
                }
            )
...
```

Video
https://github.com/stevdza-san/OneTapCompose/assets/45684749/b5c78e0e-b753-48e0-8431-39d2f13073c4

Image Log Error
![Screenshot from 2023-12-05 11-45-06](https://github.com/stevdza-san/OneTapCompose/assets/45684749/8611be62-6c76-44a3-b370-a238af82e901)

**Comment by stevdza-san** [comment]
You do need to generate a release SHA-1 fingerprint and create a new oAuth credentials for it, on Google Cloud Platform. Also if you're planning publishing your app, in the Play Console there's also a release SHA-1 fingerprint that you can use to create a new oAuth as well.

Here's the link that may help you with that error in the log: https://stackoverflow.com/questions/61768804/getting-16-cannot-find-a-matching-credential-when-doing-one-tap-sign-in-and-s

**Comment by azickri** [comment]
Okay, Thanks. I will check it out.

**Comment by stevdza-san** [comment]
I've added a new section in the readme file as well: https://github.com/stevdza-san/OneTapCompose#release-build
