### ISSUE TITLE
Developer console is not set up correctly.

### ISSUE THREAD

**Issue by 3owa** [stevdza-san/OneTapCompose#20]
Hi there can anyone help me solve this issue

**Comment by shubhamsinghshubham777** [comment]
> Hi there can anyone help me solve this issue

Could you please provide some more details about the issue? What is the error code you receive?

From the limited info we have here, maybe some of these answers will help you:
https://stackoverflow.com/questions/76823978/error-10-developer-console-is-not-set-up-correctly-not-using-firebase-one-t

**Comment by muhammedesadcomert** [comment]
It is happening in [v1.0.11](https://github.com/stevdza-san/OneTapCompose/releases/tag/1.0.11). I downgraded the version to 1.0.9 and the error is gone. The error looks like this:
<img width="40%" src="https://github.com/stevdza-san/OneTapCompose/assets/46245749/a0c554dd-38e8-45c3-bb81-73a142065abd">

**Comment by stevdza-san** [comment]
@muhammedesadcomert That error message indicates that you haven't correctly setup your project, probably it has something to do with the Google Cloud Platform project, SHA-1, Web client id? The latest v1.0.11 contains a Credential Manager underneath, but if you have some errors, feel free to use the 1.0.10.

**Comment by muhammedesadcomert** [comment]
@stevdza-san Thank you for your response. I realized forgot to add the release sha-1 key to the Firebase setup after your comment. After adding this it worked for me. For anyone else facing this issue, it might take some time to process your key after adding it. The issue can closed, thanks for your help!

**Comment by muhammedesadcomert** [comment]
Although this issue has been closed, I would like to add an explanation for those who may encounter a similar problem later. After adding both debug and release sha-1 keys to Firebase, it may seem to work properly. Still, if you publish the application on the Play Store, you must get the sha-1 key from the Play Console and add it to Firebase, as shown in the [README document](https://github.com/stevdza-san/OneTapCompose?tab=readme-ov-file#release-build). While testing your application, everything may seem fine, but if you do not have this key, signing in will not work.
