### ISSUE TITLE
[Feature Request] - Make library multiplatform

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [stevdza-san/OneTapCompose#21]
Now that the community has started utilising Compose Multiplatform more than ever before, I believe it will be beneficial for both the library and its users if `OneTapCompose` became available to all possible platforms 👍🏻 

Some other libraries are already doing this, for example Supabase's Kotlin Multiplatform Client:
https://github.com/supabase-community/supabase-kt/tree/master/plugins/ComposeAuth

**Comment by stevdza-san** [comment]
Thanks for the suggestion. Yes I'm definitely planning to do that at some point. Will leave this open for the time being.

**Comment by stevdza-san** [comment]
I've found a new library called: KMPAuth (https://github.com/mirzemehdi/KMPAuth) which you can use for Kotlin/Compose Multiplatform project. And since the library already exists, I'm not gonna bother creating another one which will do the same thing. At least not for now.
