### ISSUE TITLE
Version 1.0.11 not work on Android 14

### ISSUE THREAD

**Issue by AlessandroVendraminiDeveloper** [stevdza-san/OneTapCompose#22]
Version `1.0.11 `does not work on Android 14. (Tested on Samsung S23)
When you make the request to google via `googleLoginState.open()` nothing is shown. (The account selection dropdown does not appear.) If you press the back button, the error message (system, not from library) `access request canceled by appName` appears.
With version `1.0.10` everything works perfectly!

**Comment by stevdza-san** [comment]
Hm, that's strange, I haven't experienced such an issue. Have you checked the logs for 'OneTapCompose' tag?

**Comment by AlessandroVendraminiDeveloper** [comment]
@stevdza-san I can't read any logs because that device isn't mine and I can only test it via apk. I think is a problem with credential manager e Android 14. For example, on a One Plus 10T with Android 14 the error appears directly from the library: `Your device doesn't support credential manager`

**Comment by stevdza-san** [comment]
Hm, I guess you should file an issue to Credential Manager then. In the meanwhile keep using 1.0.10 version of OneTapCompose library. :)

**Comment by SergeyMilewski** [comment]
I confirm the same for me, it doesn't work on Android 14 Samsung S23 I mean 1.0.11
Log => `CredManProvService  I  GetCredentialResponse error returned from framework
OneTapCompose            E  No credentials available`

**Comment by stevdza-san** [comment]
Sorry for a late response. I've just published a new release 'v1.0.12', which now automatically opens up a Google Account screen to let you sign in with an account if you don't already have one. Try testing it out and let me know if it works for you. :)
