### ISSUE TITLE
dismiss: Developer console is not set up correctly.

### ISSUE THREAD

**Issue by nirazv** [stevdza-san/OneTapCompose#25]
Is that safe to call OneTapSignInWithGoogle on BottomBar of scaffold?

I am getting this error : dismiss: Developer console is not set up correctly.

`val state = rememberOneTapSignInState()

    Scaffold(
        topBar = {},
        content = { paddingValues ->
            AuthContent(
                paddingValues,
                signInState = state.opened,
                messageBarState = MessageBarState(),
                onClick = {state.open()}
            )
        },
        bottomBar = {
            OneTapSignInWithGoogle(
                state = state,
                clientId = CONSTANTS.CLIENT_ID,
                onTokenIdReceived = { tokenId ->
                    Log.d("GoogleIO", "token: $tokenId")
                },
                onDialogDismissed = { message ->
                    Log.d("GoogleIO", "dismiss: $message")
                }
            )
        }`

**Comment by stevdza-san** [comment]
You can place OneTapSignInWithGoogle composable on the top of your composable screen, outside of the scaffold, you don't have to add it inside the bottom bar. Btw that issue that you have mention probably has something to do with the way you've setup the project. Check this closed issue in this repository, it may be helpful: https://github.com/stevdza-san/OneTapCompose/issues/20

**Comment by nirazv** [comment]
I identified the issue. the issue was I created 2 API Keys Web and android and was using android in the application instead of Web, 

Replacing key valye from android to web on app worked to fix this issue.

Thanks.

Also no issue if we use this OneTapCompose on bottomBar scaffold
