### ISSUE TITLE
androidx.credentials.exceptions.Credential Exception:

### ISSUE THREAD

**Issue by shamanikrish** [stevdza-san/OneTapCompose#26]
When attempting to close the sign-in popup menu, I encountered the following error message.

androidx.credentials.exceptions.Credential Exception: During bigin sign in, failure response from one tap: 16: Caller has been temporarily blocked due to too many canceled sign-in prompts.

**Comment by stevdza-san** [comment]
Ah yeah, that can often happen if you try and cancel the dialog multiple times in a row. I suggest you looking into this answer: https://stackoverflow.com/questions/62036642/google-identity-one-tap-sign-in-exception-caller-has-been-temporarily-blacklist
