### ISSUE TITLE
FirebaseAuth integration

### ISSUE THREAD

**Issue by alorma** [stevdza-san/OneTapCompose#28]
Hi!

Following this guide: https://firebase.google.com/docs/auth/android/google-signin#kotlin+ktx_4

I successfully used this library (awesome) to authenticate the user through `FirebaseAuth`.

As simple as:

```kotlin
  OneTapSignInWithGoogle(
    state = state,
    clientId = stringResource(R.string.web_client_id),
    onTokenIdReceived = { tokenId ->
      val firebaseCredential = GoogleAuthProvider.getCredential(tokenId, null)
      Firebase.auth.signInWithCredential(firebaseCredential).addOnCompleteListener { task ->
        if (task.isSuccessful) {
          onUserAuthenticated() // Firebase.auth.currentUser is already set at this point
        } else {
          // Error
        }
      }
    },
    onDialogDismissed = { message ->

    }
  )
```

Do you think that this could be integrated into the library? Maybe in a way that allows user to plugs the "obtain user" way.

I mean:

```kotlin
OneTapSignInWithGoogle(
    state = state,
    clientId = stringResource(R.string.web_client_id),
    userProvider = oneTapUserProvider(onUserObtained = { it: GoogleUser -> })
)

OneTapSignInWithGoogle(
    state = state,
    clientId = stringResource(R.string.web_client_id),
    userProvider = firebaseAuthUserProvider(onUserObtained = { it: FirebaseUser -> })
)
```

I could try to build up a PR for this, if you find it could be useful.

**Comment by stevdza-san** [comment]
Feel free to submit a PR, and I'll take a look. Be sure to add the docs in the readme. 
However I wouldn't change the current API which uses a onTokenIdReceived {} lambda, instead you could made another 'optional parameter' for the userProvider. Thanks for the example btw. :)
