### ISSUE TITLE
state.open() dont't works

### ISSUE THREAD

**Issue by fernandomflopes** [stevdza-san/OneTapCompose#29]
Hello,
When I close the login pop-up, I can't reopen it using state.open().

**Comment by stevdza-san** [comment]
Have you checked the logs with 'OneTapCompose' tag? You may have closed the sign in popup multiple times in a row, which resulted in blocked requests.

**Comment by sikanderkhcb** [comment]
Same issue with me but there is no log print .

**Comment by stevdza-san** [comment]
The open() function may be blocked if you have tried closing the dialog multiple times in a short period of time. That's an automated behavior, which blocks you from abusing the service. You can check this answer for more information: https://stackoverflow.com/questions/76671700/android-google-one-tap-in-jetpack-compose

Btw, you should be able to see some related logs, try checking in more details?

**Comment by sikanderkhcb** [comment]
Thanks for replying 
i just compile your sample project with replacing my Web client ID but circleprogress is running continuously and nothing happen.

**Comment by stevdza-san** [comment]
You need to check the logs and see more details when you trigger the open() function. Usually that issue can happen if Credentials Manager is not available on a device. I'll work on a new release where you can directly receive a callback when that issue occurs.
