### ISSUE TITLE
FragmentContextWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by Cerverussz** [stevdza-san/OneTapCompose#4]
calling OneTapSignInWithGoogle from a fragment gives this error

java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity

![image](https://user-images.githubusercontent.com/28854287/230210756-2e70aa91-2488-40f6-9a25-52aa971cbd13.png)

**Comment by stevdza-san** [comment]
I've made this library primarily for usage with Compose Activity. I haven't actually tested it with Fragments. You can check the source code and try to experiment with it a bit. :)

**Comment by Cerverussz** [comment]
Yes sir, the solution was:

add the context as a parameter and from the fragment, it is sent as requireActivity()

Thank you very much and see you soon :D
