### ISSUE TITLE
Only "Dialog Closed" Debug Message Shown

### ISSUE THREAD

**Issue by Fernker** [stevdza-san/OneTapCompose#5]
I've connected it as directed (although probably still have something wrong somewhere).

I've moved to a real device because of the "Google Account Not Found"

But when I try to sign-in I get the prompt and click "Continue As <name>" button I only get a "Dialog Closed" message.

Looking at your code is there someway to get more detailed information about why the "Dialog Closed" message is showing?   Is there anymore information that could be surfaced for debugging?

**Comment by stevdza-san** [comment]
That specific message is shown only after a result of a ActivityResultContracts is NOT "Activity.RESULT_OK". Here's the link: https://github.com/stevdza-san/OneTapCompose/blob/master/onetap/src/main/java/com/stevdzasan/onetap/OneTapCompose.kt#L55

**Comment by Fernker** [comment]
Thanks I was able to clone your code in and see what the activity result was, it was coming back as CANCELLED.  Is there any useful degbugging data on the intent that comes back from that activity?  It really is a black box with such a generic message and not having any further data/errors to Google from.

**Comment by Fernker** [comment]
Like for example I was getting `Google Account not Found.` error and I added a `Log.d` to log the exception on the `addOnFailureListener`.  I got a lot better error `com.google.android.gms.common.api.ApiException: 16: Caller has been temporarily blocked due to too many canceled sign-in prompts.`

So it feels like this library still might need to surface the real errors

**Comment by stevdza-san** [comment]
Thanks for mentioning that, I'll soon push a new update!

**Comment by stevdza-san** [comment]
Done.

**Comment by Fernker** [comment]
Thank you!

**Comment by azickri** [comment]
I got this error when I clicked select account, suddenly the dialog disappeared and the error message Dialog Closed appeared
Can anyone help?

NOTE
I got it, should use context.getString(R.string.client_id) not use R.string.client_id.toString()

**Comment by stevdza-san** [comment]
@azickri Check the logs under the tag with the name: "OneTapCompose", it contains some additional information about the issue you're encountering.

**Comment by azickri** [comment]
@stevdza-san  Thanks, maybe you can add that flag of log di Readme, so people can reach out.

As for the accessToken generated from OneTapCompose, why can't it be used for the Normal API?

I try to Hit API https://www.googleapis.com/oauth2/v1/userinfo with token from OneTapCompose but got return 401.

Have you ever tried it?

**Comment by stevdza-san** [comment]
@azickri Thanks I'll be sure to add that information in the readme file. :)
Maybe you're missing some request header information along with that. The easiest way to test the "Token Id" is with https://jwt.io/

**Comment by azickri** [comment]
Okay, i will test again soon.. I will convey the results later.
Maybe I'll send you a Video
