### ISSUE TITLE
[BeginSignInOperation] Operation failed. 

### ISSUE THREAD

**Issue by ThakurVibha** [stevdza-san/OneTapCompose#8]
[BeginSignInOperation] Operation failed. 
getting Google Account not Found,
First time it worked fine but after that i am not able to signin again, dialog not showing  even if i am using on real device.

**Comment by stevdza-san** [comment]
Do you have some more error information except that?

**Comment by ThakurVibha** [comment]
okay, its working now i made a silly mistake in code

**Comment by ThakurVibha** [comment]
okay, its working now i made a silly mistake in code
